### ISSUE TITLE
Make the UI more pleasing and properly formatted

### ISSUE THREAD

**Issue by onlykingKD** [manavgoyal111/placement-2023#2]
You are free to use any third-party library to make UI look better and pleasing

**Comment by ansarisaqlain987** [comment]
Hi @onlykingKD. I want to contribute to this repository. Can you assign this issue to me?

**Comment by ansarisaqlain987** [comment]
@onlykingKD  I have created a PR for this issue, request you to review the same.
https://github.com/manavgoyal111/placement-2023/pull/14

**Comment by onlykingKD** [comment]
@ansarisaqlain987 Thanks for the contribution. The UI looks so much better now. loved it. 👏💯
