### ISSUE TITLE
Remove the footer text and center the social media icons

### ISSUE THREAD

**Issue by primeTanM** [manavgoyal111/placement-2023#4]
Remove the footer text "Get connected on social networks" and center the social media icons.

Also add hover effects on the icons

**Comment by teeshaa** [comment]
@primeTanM Please assign me this issue. I would like to edit this.

**Comment by karthickbharathi1** [comment]
Hey @onlykingKD  @primeTanM . Can you assign this issue to me? I had resolved this issue and made a PR.
