### ISSUE TITLE
Add 2 Linkedin/Instagram Profiles hyperlink with icons in footer

### ISSUE THREAD

**Issue by onlykingKD** [manavgoyal111/placement-2023#5]
https://www.linkedin.com/in/manav-goyal/
https://www.linkedin.com/in/kaustubhdwivedi1729/

**Comment by GoSleepBelall** [comment]
Hi, I'm interested in this, can you please assign me this task?

**Comment by GoSleepBelall** [comment]
![image](https://github.com/manavgoyal111/placement-2023/assets/86932331/8ded4da1-fb63-4a2d-8c43-397c2c13665c)
There is one linkedIn icon, working fine with (https://www.linkedin.com/in/manav-goyal/).
Do I have to add another Icon there with second link?

**Comment by onlykingKD** [comment]
yeah add a second one also
