### ISSUE TITLE
Implement Sorting

### ISSUE THREAD

**Issue by onlykingKD** [manavgoyal111/placement-2023#8]
Add two buttons/checkboxes in header

1) **Sort By CTC** -  Descending Order

CTC is in string format- 
if it is a+b, while sorting sum should be taken in consideration,
if it is a/b while sorting max(a,b) should be taken in consoderation
refer to this
https://github.com/manavgoyal111/placement-2023/blob/d633ae56d10d76bfe7b5430252a1ba3cb1bf2cc7/src/App.js#L20

2) **Sort By Company Name** - Ascending Order

**Comment by prane-eth** [comment]
Can I start to work?

**Comment by prane-eth** [comment]
Here is a pull request: #18 
https://github.com/manavgoyal111/placement-2023/pull/18/

**Comment by onlykingKD** [comment]
@prane-eth Thanks for the contribution.
